apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: "2020-05-13T19:03:45Z"
  generation: 40
  labels:
    app.kubernetes.io/instance: emqx
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: emqx
    helm.sh/chart: emqx-v4.0.5
  name: emqx
  namespace: default
  resourceVersion: "50661047"
  selfLink: /apis/apps/v1/namespaces/default/statefulsets/emqx
  uid: 86e7d2a6-4dba-44f0-abbb-751ba8393e21
spec:
  podManagementPolicy: OrderedReady
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: emqx
      app.kubernetes.io/name: emqx
  serviceName: emqx-headless
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: emqx
        app.kubernetes.io/name: emqx
    spec:
      containers:
      - env:
        - name: EMQX_NAME
          value: emqx
        - name: EMQX_CLUSTER__K8S__APP_NAME
          value: emqx
        - name: EMQX_CLUSTER__DISCOVERY
          value: k8s
        - name: EMQX_CLUSTER__K8S__SERVICE_NAME
          value: emqx-headless
        - name: EMQX_CLUSTER__K8S__NAMESPACE
          value: default
        envFrom:
        - configMapRef:
            name: emqx-env
        image: emqx/emqx:v4.0.5
        imagePullPolicy: IfNotPresent
        name: emqx
        ports:
        - containerPort: 1883
          protocol: TCP
        - containerPort: 8883
          protocol: TCP
        - containerPort: 8081
          protocol: TCP
        - containerPort: 8083
          protocol: TCP
        - containerPort: 8084
          protocol: TCP
        - containerPort: 18083
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /status
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "4"
          requests:
            cpu: "4"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/emqx/data/mnesia
          name: emqx-data
      dnsPolicy: ClusterFirst
      nodeSelector:
        rtpatch: "false"
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1000
      serviceAccount: emqx
      serviceAccountName: emqx
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: emqx-data
  updateStrategy:
    type: RollingUpdate
status:
  collisionCount: 0
  currentReplicas: 3
  currentRevision: emqx-7cc7bfbc5d
  observedGeneration: 40
  readyReplicas: 3
  replicas: 3
  updateRevision: emqx-7cc7bfbc5d
  updatedReplicas: 3
