apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: "2020-04-13T06:02:08Z"
  generation: 157
  labels:
    app.kubernetes.io/instance: vernemq
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: vernemq
    helm.sh/chart: vernemq-1.6.2
  name: vernemq
  namespace: default
  resourceVersion: "50660905"
  selfLink: /apis/apps/v1/namespaces/default/statefulsets/vernemq
  uid: becd350f-ab90-4ac0-b681-17e7b7f181ff
spec:
  podManagementPolicy: OrderedReady
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: vernemq
      app.kubernetes.io/name: vernemq
  serviceName: vernemq-headless
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: vernemq
        app.kubernetes.io/name: vernemq
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - vernemq
                - key: release
                  operator: In
                  values:
                  - vernemq
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: DOCKER_VERNEMQ_DISCOVERY_KUBERNETES
          value: "1"
        - name: DOCKER_VERNEMQ_KUBERNETES_LABEL_SELECTOR
          value: app.kubernetes.io/name=vernemq,app.kubernetes.io/instance=vernemq
        - name: DOCKER_VERNEMQ_LISTENER__TCP__LOCALHOST
          value: 127.0.0.1:1883
        - name: DOCKER_VERNEMQ_MAX_CLIENT_ID_SIZE
          value: "100"
        - name: DOCKER_VERNEMQ_MAX_ONLINE_MESSAGES
          value: "50000"
        - name: DOCKER_VERNEMQ_MAX_OFFLINE_MESSAGES
          value: "50000"
        - name: DOCKER_VERNEMQ_MAX_INFLIGHT_MESSAGES
          value: "1000"
        - name: DOCKER_VERNEMQ_LISTENER__SSL__DEFAULT
          value: $(MY_POD_IP):8883
        - name: DOCKER_VERNEMQ_ACCEPT_EULA
          value: "yes"
        - name: DOCKER_VERNEMQ_ALLOW_REGISTER_DURING_NETSPLIT
          value: "on"
        - name: DOCKER_VERNEMQ_ALLOW_PUBLISH_DURING_NETSPLIT
          value: "on"
        - name: DOCKER_VERNEMQ_ALLOW_SUBSCRIBE_DURING_NETSPLIT
          value: "on"
        - name: DOCKER_VERNEMQ_ALLOW_UNSUBSCRIBE_DURING_NETSPLIT
          value: "on"
        - name: DOCKER_VERNEMQ_ALLOW_ANONYMOUS
          value: "on"
        - name: DOCKER_VERNEMQ_LISTENER__SSL__CAFILE
          value: /etc/ssl/vernemq/all-ca.crt
        - name: DOCKER_VERNEMQ_LISTENER__SSL__CERTFILE
          value: /etc/ssl/vernemq/server.crt
        - name: DOCKER_VERNEMQ_LISTENER__SSL__KEYFILE
          value: /etc/ssl/vernemq/server.key
        - name: DOCKER_VERNEMQ_LISTENER__SSL__LOCALHOST
          value: 127.0.0.1:8883
        - name: DOCKER_VERNEMQ_LISTENER__SSL__DEFAULT__REQUIRE_CERTIFICATE
          value: "off"
        - name: DOCKER_VERNEMQ_LISTENER__SSL__DEFAULT__USE_IDENTITY_AS_USERNAME
          value: "off"
        - name: DOCKER_VERNEMQ_LISTENER__SSL__LOCALHOST__USE_IDENTITY_AS_USERNAME
          value: "off"
        - name: DOCKER_VERNEMQ_LISTENER__SSL__LOCALHOST__REQUIRE_CERTIFICATE
          value: "off"
        image: vernemq/vernemq:1.10.2-1-alpine
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: prometheus
            scheme: HTTP
          initialDelaySeconds: 90
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: vernemq
        ports:
        - containerPort: 1883
          name: mqtt
          protocol: TCP
        - containerPort: 8883
          name: mqtts
          protocol: TCP
        - containerPort: 4369
          name: epmd
          protocol: TCP
        - containerPort: 44053
          name: vmq
          protocol: TCP
        - containerPort: 8080
          name: ws
          protocol: TCP
        - containerPort: 8888
          name: prometheus
          protocol: TCP
        - containerPort: 9100
          protocol: TCP
        - containerPort: 9101
          protocol: TCP
        - containerPort: 9102
          protocol: TCP
        - containerPort: 9103
          protocol: TCP
        - containerPort: 9104
          protocol: TCP
        - containerPort: 9105
          protocol: TCP
        - containerPort: 9106
          protocol: TCP
        - containerPort: 9107
          protocol: TCP
        - containerPort: 9108
          protocol: TCP
        - containerPort: 9109
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: prometheus
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "8"
          requests:
            cpu: "8"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /vernemq/log
          name: logs
        - mountPath: /vernemq/data
          name: data
        - mountPath: /etc/ssl/vernemq
          name: vernemq-certificates
          readOnly: true
      dnsPolicy: ClusterFirst
      nodeSelector:
        rtpatch: "false"
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 10000
        runAsGroup: 10000
        runAsUser: 10000
      serviceAccount: vernemq
      serviceAccountName: vernemq
      terminationGracePeriodSeconds: 60
      volumes:
      - emptyDir: {}
        name: logs
      - name: vernemq-certificates
        secret:
          defaultMode: 420
          secretName: vernemq-certificates-secret
      - emptyDir: {}
        name: data
  updateStrategy:
    type: RollingUpdate
status:
  collisionCount: 0
  currentReplicas: 2
  currentRevision: vernemq-86976c5cfb
  observedGeneration: 157
  readyReplicas: 2
  replicas: 2
  updateRevision: vernemq-86976c5cfb
  updatedReplicas: 2
