apiVersion: v1
kind: ReplicationController
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ReplicationController","metadata":{"annotations":{},"name":"hivemq-replica","namespace":"default"},"spec":{"replicas":3,"selector":{"app":"hivemq-cluster1"},"template":{"metadata":{"labels":{"app":"hivemq-cluster1"},"name":"hivemq-cluster1"},"spec":{"containers":[{"env":[{"name":"HIVEMQ_DNS_DISCOVERY_ADDRESS","value":"hivemq-discovery.default.svc.cluster.local."},{"name":"HIVEMQ_DNS_DISCOVERY_TIMEOUT","value":"20"},{"name":"HIVEMQ_DNS_DISCOVERY_INTERVAL","value":"21"}],"image":"hivemq/hivemq3:dns-latest","livenessProbe":{"failureThreshold":60,"initialDelaySeconds":30,"periodSeconds":60,"tcpSocket":{"port":1883}},"name":"hivemq-pods","ports":[{"containerPort":8080,"name":"web-ui","protocol":"TCP"},{"containerPort":1883,"name":"mqtt","protocol":"TCP"}],"readinessProbe":{"failureThreshold":60,"initialDelaySeconds":30,"periodSeconds":60,"tcpSocket":{"port":1883}}}]}}}}
  creationTimestamp: "2020-04-10T17:34:49Z"
  generation: 184
  labels:
    app: hivemq-cluster1
  name: hivemq-replica
  namespace: default
  resourceVersion: "50658750"
  selfLink: /api/v1/namespaces/default/replicationcontrollers/hivemq-replica
  uid: 1bcca38c-e70a-424e-885a-04fce421dfe0
spec:
  replicas: 2
  selector:
    app: hivemq-cluster1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hivemq-cluster1
      name: hivemq-cluster1
    spec:
      containers:
      - env:
        - name: HIVEMQ_DNS_DISCOVERY_ADDRESS
          value: hivemq-discovery.default.svc.cluster.local.
        - name: HIVEMQ_DNS_DISCOVERY_TIMEOUT
          value: "20"
        - name: HIVEMQ_DNS_DISCOVERY_INTERVAL
          value: "21"
        - name: HIVEMQ_INFLIGHT
          value: "1000"
        image: abbiotcontainerregistry.azurecr.io/hivemq-tls:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 60
          initialDelaySeconds: 30
          periodSeconds: 60
          successThreshold: 1
          tcpSocket:
            port: 1883
          timeoutSeconds: 1
        name: hivemq-pods
        ports:
        - containerPort: 8080
          name: web-ui
          protocol: TCP
        - containerPort: 1883
          name: mqtt
          protocol: TCP
        - containerPort: 8883
          name: mqtt-ssl
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 1883
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "8"
          requests:
            cpu: "8"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: abbiotcontainerregistrysecret
      nodeSelector:
        rtpatch: "false"
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 2
  fullyLabeledReplicas: 2
  observedGeneration: 184
  readyReplicas: 2
  replicas: 2
